// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: camion.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Paquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tipo    string `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Valor   int64  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen  string `protobuf:"bytes,4,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *Paquete) Reset() {
	*x = Paquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paquete) ProtoMessage() {}

func (x *Paquete) ProtoReflect() protoreflect.Message {
	mi := &file_camion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paquete.ProtoReflect.Descriptor instead.
func (*Paquete) Descriptor() ([]byte, []int) {
	return file_camion_proto_rawDescGZIP(), []int{0}
}

func (x *Paquete) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Paquete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Paquete) GetValor() int64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Paquete) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *Paquete) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

type Reporte struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Intentos  int64  `protobuf:"varint,2,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Tipo      string `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Entregado bool   `protobuf:"varint,4,opt,name=entregado,proto3" json:"entregado,omitempty"`
}

func (x *Reporte) Reset() {
	*x = Reporte{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reporte) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reporte) ProtoMessage() {}

func (x *Reporte) ProtoReflect() protoreflect.Message {
	mi := &file_camion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reporte.ProtoReflect.Descriptor instead.
func (*Reporte) Descriptor() ([]byte, []int) {
	return file_camion_proto_rawDescGZIP(), []int{1}
}

func (x *Reporte) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reporte) GetIntentos() int64 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *Reporte) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Reporte) GetEntregado() bool {
	if x != nil {
		return x.Entregado
	}
	return false
}

type RespuestaPedido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reportes []*Reporte `protobuf:"bytes,1,rep,name=reportes,proto3" json:"reportes,omitempty"`
	Mensaje  []string   `protobuf:"bytes,2,rep,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *RespuestaPedido) Reset() {
	*x = RespuestaPedido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaPedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaPedido) ProtoMessage() {}

func (x *RespuestaPedido) ProtoReflect() protoreflect.Message {
	mi := &file_camion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaPedido.ProtoReflect.Descriptor instead.
func (*RespuestaPedido) Descriptor() ([]byte, []int) {
	return file_camion_proto_rawDescGZIP(), []int{2}
}

func (x *RespuestaPedido) GetReportes() []*Reporte {
	if x != nil {
		return x.Reportes
	}
	return nil
}

func (x *RespuestaPedido) GetMensaje() []string {
	if x != nil {
		return x.Mensaje
	}
	return nil
}

type PedidoDespacho struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paquetes []*Paquete `protobuf:"bytes,1,rep,name=paquetes,proto3" json:"paquetes,omitempty"`
}

func (x *PedidoDespacho) Reset() {
	*x = PedidoDespacho{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camion_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PedidoDespacho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedidoDespacho) ProtoMessage() {}

func (x *PedidoDespacho) ProtoReflect() protoreflect.Message {
	mi := &file_camion_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedidoDespacho.ProtoReflect.Descriptor instead.
func (*PedidoDespacho) Descriptor() ([]byte, []int) {
	return file_camion_proto_rawDescGZIP(), []int{3}
}

func (x *PedidoDespacho) GetPaquetes() []*Paquete {
	if x != nil {
		return x.Paquetes
	}
	return nil
}

type Disponibilidad struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camion int64 `protobuf:"varint,1,opt,name=camion,proto3" json:"camion,omitempty"`
}

func (x *Disponibilidad) Reset() {
	*x = Disponibilidad{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camion_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Disponibilidad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disponibilidad) ProtoMessage() {}

func (x *Disponibilidad) ProtoReflect() protoreflect.Message {
	mi := &file_camion_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disponibilidad.ProtoReflect.Descriptor instead.
func (*Disponibilidad) Descriptor() ([]byte, []int) {
	return file_camion_proto_rawDescGZIP(), []int{4}
}

func (x *Disponibilidad) GetCamion() int64 {
	if x != nil {
		return x.Camion
	}
	return 0
}

type RespuestaDisponibilidad struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta bool `protobuf:"varint,1,opt,name=respuesta,proto3" json:"respuesta,omitempty"`
}

func (x *RespuestaDisponibilidad) Reset() {
	*x = RespuestaDisponibilidad{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camion_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaDisponibilidad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaDisponibilidad) ProtoMessage() {}

func (x *RespuestaDisponibilidad) ProtoReflect() protoreflect.Message {
	mi := &file_camion_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaDisponibilidad.ProtoReflect.Descriptor instead.
func (*RespuestaDisponibilidad) Descriptor() ([]byte, []int) {
	return file_camion_proto_rawDescGZIP(), []int{5}
}

func (x *RespuestaDisponibilidad) GetRespuesta() bool {
	if x != nil {
		return x.Respuesta
	}
	return false
}

var File_camion_proto protoreflect.FileDescriptor

var file_camion_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x07, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x70, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67,
	0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x22, 0x67, 0x0a, 0x07,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x65,
	0x67, 0x61, 0x64, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x72,
	0x65, 0x67, 0x61, 0x64, 0x6f, 0x22, 0x57, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x2a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x22, 0x3c,
	0x0a, 0x0e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x44, 0x65, 0x73, 0x70, 0x61, 0x63, 0x68, 0x6f,
	0x12, 0x2a, 0x0a, 0x08, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65,
	0x74, 0x65, 0x52, 0x08, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0e,
	0x44, 0x69, 0x73, 0x70, 0x6f, 0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x64, 0x61, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x44, 0x69, 0x73, 0x70, 0x6f, 0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x64, 0x61,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x32,
	0x89, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x43, 0x61, 0x6d, 0x69,
	0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x09, 0x44, 0x65, 0x73, 0x70, 0x61, 0x63, 0x68, 0x61, 0x72, 0x12,
	0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x1a,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x42, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6c, 0x74, 0x61, 0x72, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x73,
	0x70, 0x6f, 0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x64, 0x61, 0x64, 0x1a, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x44, 0x69, 0x73,
	0x70, 0x6f, 0x6e, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x64, 0x61, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_camion_proto_rawDescOnce sync.Once
	file_camion_proto_rawDescData = file_camion_proto_rawDesc
)

func file_camion_proto_rawDescGZIP() []byte {
	file_camion_proto_rawDescOnce.Do(func() {
		file_camion_proto_rawDescData = protoimpl.X.CompressGZIP(file_camion_proto_rawDescData)
	})
	return file_camion_proto_rawDescData
}

var file_camion_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_camion_proto_goTypes = []interface{}{
	(*Paquete)(nil),                 // 0: proto.Paquete
	(*Reporte)(nil),                 // 1: proto.Reporte
	(*RespuestaPedido)(nil),         // 2: proto.RespuestaPedido
	(*PedidoDespacho)(nil),          // 3: proto.PedidoDespacho
	(*Disponibilidad)(nil),          // 4: proto.Disponibilidad
	(*RespuestaDisponibilidad)(nil), // 5: proto.RespuestaDisponibilidad
}
var file_camion_proto_depIdxs = []int32{
	1, // 0: proto.RespuestaPedido.reportes:type_name -> proto.Reporte
	0, // 1: proto.PedidoDespacho.paquetes:type_name -> proto.Paquete
	0, // 2: proto.ServicioCamion.Despachar:input_type -> proto.Paquete
	4, // 3: proto.ServicioCamion.Consultar:input_type -> proto.Disponibilidad
	2, // 4: proto.ServicioCamion.Despachar:output_type -> proto.RespuestaPedido
	5, // 5: proto.ServicioCamion.Consultar:output_type -> proto.RespuestaDisponibilidad
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_camion_proto_init() }
func file_camion_proto_init() {
	if File_camion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_camion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reporte); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaPedido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camion_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PedidoDespacho); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camion_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Disponibilidad); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camion_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaDisponibilidad); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_camion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_camion_proto_goTypes,
		DependencyIndexes: file_camion_proto_depIdxs,
		MessageInfos:      file_camion_proto_msgTypes,
	}.Build()
	File_camion_proto = out.File
	file_camion_proto_rawDesc = nil
	file_camion_proto_goTypes = nil
	file_camion_proto_depIdxs = nil
}
